import { Component, OnInit, inject, input, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { Router, RouterLink } from '@angular/router';

import { BlogApiService, fileToRoBlob, PostView, RoBlobValue } from '../../core/blog-api.service';
import { MessagesService } from '../../core/messages.service';
import { RoError } from '../../core/ro.types';

type Panel = 'none' | 'rename' | 'editContent' | 'editPicture' | 'editDescription';

@Component({
  selector: 'app-post-detail',
  imports: [FormsModule, RouterLink],
  templateUrl: './post-detail.html',
  styleUrl: './post-detail.css',
})
export class PostDetail implements OnInit {
  private readonly api = inject(BlogApiService);
  private readonly messages = inject(MessagesService);
  private readonly router = inject(Router);
  private readonly sanitizer = inject(DomSanitizer);

  readonly id = input.required<string>();

  readonly post = signal<PostView | null>(null);
  readonly loading = signal(true);
  readonly panel = signal<Panel>('none');
  readonly busy = signal(false);
  readonly fieldErrors = signal<Record<string, string>>({});

  // The previews are HTML generated by our own backend (ImageSupport /
  // MarkupSupport, which sanitize user input server-side), so trusting
  // them here does not introduce new script surface.
  readonly picturePreview = signal<SafeHtml | null>(null);
  readonly contentPreview = signal<SafeHtml | null>(null);

  renameValue = '';
  contentValue = '';
  descriptionValue = '';
  pictureDescriptionValue = '';
  pictureFile: File | null = null;

  async ngOnInit(): Promise<void> {
    await this.refresh();
  }

  async refresh(): Promise<void> {
    this.loading.set(true);
    try {
      this.apply(await this.api.getPost(this.id()));
    } catch (error) {
      this.messages.error(this.describe(error, 'Could not load the post'));
    } finally {
      this.loading.set(false);
    }
  }

  disabledReason(memberId: string): string | null {
    return this.post()?.disabled[memberId] ?? null;
  }

  openPanel(panel: Panel): void {
    this.fieldErrors.set({});
    this.panel.set(this.panel() === panel ? 'none' : panel);
    const post = this.post();
    if (panel === 'rename') {
      this.renameValue = post?.name ?? '';
    }
    if (panel === 'editContent') {
      this.contentValue = post?.content ?? '';
    }
    if (panel === 'editDescription') {
      this.descriptionValue = post?.pictureDescription ?? '';
    }
    if (panel === 'editPicture') {
      this.pictureFile = null;
      this.pictureDescriptionValue = post?.pictureDescription ?? '';
    }
  }

  onPictureSelected(event: Event): void {
    const files = (event.target as HTMLInputElement).files;
    this.pictureFile = files && files.length > 0 ? files[0] : null;
  }

  async rename(): Promise<void> {
    await this.run(async () => {
      this.apply(await this.api.renamePost(this.id(), this.renameValue.trim()));
      this.panel.set('none');
      this.messages.info('Post renamed');
    });
  }

  async saveContent(): Promise<void> {
    await this.run(async () => {
      await this.api.updatePostContent(this.id(), this.contentValue.trim() || null);
      this.panel.set('none');
      this.messages.info('Content updated');
      await this.refresh();
    });
  }

  async saveDescription(): Promise<void> {
    await this.run(async () => {
      await this.api.updatePictureDescription(this.id(), this.descriptionValue.trim() || null);
      this.panel.set('none');
      this.messages.info('Picture description updated');
      await this.refresh();
    });
  }

  async savePicture(): Promise<void> {
    await this.run(async () => {
      let picture: RoBlobValue | null = null;
      if (this.pictureFile) {
        picture = await fileToRoBlob(this.pictureFile);
      }
      this.apply(
        await this.api.updatePicture(
          this.id(),
          picture,
          this.pictureDescriptionValue.trim() || null,
        ),
      );
      this.panel.set('none');
      this.messages.info('Picture updated');
    });
  }

  async clearPicture(): Promise<void> {
    if (!confirm('Remove this post’s picture and picture description?')) {
      return;
    }
    await this.run(async () => {
      this.apply(await this.api.clearPicture(this.id()));
      this.messages.info('Picture cleared');
    });
  }

  async deletePost(): Promise<void> {
    const post = this.post();
    if (!post || !confirm(`Delete post '${post.title}'?`)) {
      return;
    }
    await this.run(async () => {
      const blogId = post.blogRef?.instanceId;
      await this.api.deletePost(this.id());
      this.messages.info(`'${post.title}' deleted`);
      await this.router.navigate(blogId ? ['/blogs', blogId] : ['/']);
    });
  }

  private apply(post: PostView): void {
    this.post.set(post);
    this.picturePreview.set(
      post.picturePreviewHtml
        ? this.sanitizer.bypassSecurityTrustHtml(post.picturePreviewHtml)
        : null,
    );
    this.contentPreview.set(
      post.contentPreviewHtml
        ? this.sanitizer.bypassSecurityTrustHtml(post.contentPreviewHtml)
        : null,
    );
  }

  private async run(work: () => Promise<void>): Promise<void> {
    this.busy.set(true);
    this.fieldErrors.set({});
    try {
      await work();
    } catch (error) {
      if (error instanceof RoError && error.validation) {
        this.fieldErrors.set(error.validation.params);
        if (Object.keys(error.validation.params).length === 0) {
          this.messages.error(error.validation.general ?? error.message);
        }
      } else {
        this.messages.error(this.describe(error, 'The action failed'));
      }
    } finally {
      this.busy.set(false);
    }
  }

  private describe(error: unknown, fallback: string): string {
    return error instanceof RoError ? error.message : fallback;
  }
}
